FROM python:3.11-slim

WORKDIR /app

ENV PATH="/usr/local/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

COPY ./api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install uvicorn

COPY ./api/app /app/app

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]